import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';import { MatCardModule } from '@angular/material/card';import { MatFormFieldModule } from '@angular/material/form-field';import { MatInputModule } from '@angular/material/input';
import { finalize } from 'rxjs';import { AccountAccessService, SpaceMember } from '../identity/account-access.service';import { Category, CategoryService } from '../expenses/category.service';import { Recurrence, RecurrenceChange, RecurrenceChangeResult, RecurrenceForecast, RecurrenceFrequency, RecurrenceService, RecurrenceValueType } from './recurrence.service';import { RecurrenceEditComponent } from './recurrence-edit.component';
@Component({selector:'app-recurrence',imports:[ReactiveFormsModule,RouterLink,MatButtonModule,MatCardModule,MatFormFieldModule,MatInputModule,RecurrenceEditComponent],templateUrl:'./recurrence.component.html',styleUrl:'./recurrence.component.scss'})
export class RecurrenceComponent implements OnInit {
  private readonly fb=inject(FormBuilder);private readonly api=inject(RecurrenceService);private readonly categoriesApi=inject(CategoryService);private readonly identity=inject(AccountAccessService);
  readonly categories=signal<Category[]>([]);readonly members=signal<SpaceMember[]>([]);readonly recurrences=signal<Recurrence[]>([]);readonly forecasts=signal<RecurrenceForecast[]>([]);readonly forecastPeriod=signal('');readonly previewDates=signal<string[]>([]);readonly loading=signal(true);readonly forecastLoading=signal(true);readonly submitting=signal(false);readonly anticipating=signal<string|null>(null);readonly anticipatedExpenseId=signal<string|null>(null);readonly message=signal<string|null>(null);readonly error=signal<string|null>(null);private key=this.api.newIdempotencyKey();
  readonly confirmingForecast=signal<RecurrenceForecast|null>(null);readonly confirmError=signal<string|null>(null);private confirmKey='';
  readonly confirmAmount=this.fb.nonNullable.control('',[Validators.required,Validators.pattern(/^\d{1,8}([.,]\d{1,2})?$/),c=>c.value&&Number(String(c.value).replace(',','.'))<=0?{positive:true}:null]);
  readonly form=this.fb.nonNullable.group({description:['',[Validators.required,Validators.maxLength(200)]],amount:['',[Validators.required,Validators.pattern(/^\d{1,8}([.,]\d{1,2})?$/)]],valueType:['FIXED' as RecurrenceValueType,Validators.required],frequency:['MONTHLY' as RecurrenceFrequency,Validators.required],firstDueDate:['',Validators.required],lastDueDate:[''],categoryId:[''],responsibleUserId:['']});
  ngOnInit(){this.categoriesApi.list(false).subscribe(v=>this.categories.set(v));this.identity.members().subscribe(v=>this.members.set(v));this.load();this.loadForecasts();}
  preview(){if(this.form.controls.firstDueDate.invalid){this.form.controls.firstDueDate.markAsTouched();return;}const v=this.form.getRawValue();this.api.preview({firstDueDate:v.firstDueDate,lastDueDate:v.lastDueDate||null,frequency:v.frequency}).subscribe({next:d=>{this.previewDates.set(d);this.error.set(null);},error:e=>this.handle(e,'Não foi possível calcular o calendário.')});}
  submit(){if(this.form.invalid||this.submitting()){this.form.markAllAsTouched();return;}const v=this.form.getRawValue();this.submitting.set(true);this.error.set(null);this.api.create({...v,amount:v.amount.replace(',','.'),lastDueDate:v.lastDueDate||null,categoryId:v.categoryId||null,responsibleUserId:v.responsibleUserId||null},this.key).pipe(finalize(()=>this.submitting.set(false))).subscribe({next:r=>{this.message.set('Recorrência cadastrada. Se houver vencimento no mês atual, o lançamento aparecerá em Despesas em até 30 segundos.');this.previewDates.set(r.previewDates);this.key=this.api.newIdempotencyKey();this.form.reset({description:'',amount:'',valueType:'FIXED',frequency:'MONTHLY',firstDueDate:'',lastDueDate:'',categoryId:'',responsibleUserId:''});this.load(false);this.loadForecasts();},error:e=>this.handle(e,'Não foi possível cadastrar a recorrência.')});}
  frequencyLabel(v:RecurrenceFrequency){return {MONTHLY:'Mensal',BIMONTHLY:'Bimestral',QUARTERLY:'Trimestral',SEMIANNUAL:'Semestral',ANNUAL:'Anual'}[v];}valueLabel(v:RecurrenceValueType){return v==='FIXED'?'Valor fixo':'Estimativa variável a confirmar';}
  anticipate(item:RecurrenceForecast){if(this.anticipating()||!window.confirm(`Antecipar o lançamento de ${item.description} com vencimento previsto em ${item.scheduledDueDate}?`))return;const key=this.api.newIdempotencyKey();this.anticipating.set(`${item.recurrenceId}:${item.scheduledDueDate}`);this.error.set(null);this.api.anticipate(item,key).pipe(finalize(()=>this.anticipating.set(null))).subscribe({next:r=>{this.message.set('Lançamento antecipado sem alterar o calendário da recorrência.');this.anticipatedExpenseId.set(r.occurrence.expenseId);this.loadForecasts();},error:e=>this.handle(e,'Não foi possível antecipar o lançamento.')});}
  canConfirm(item:RecurrenceForecast){return item.state==='FORECAST'&&item.estimated;}
  openConfirm(item:RecurrenceForecast){this.confirmingForecast.set(item);this.confirmError.set(null);this.confirmKey=this.api.newIdempotencyKey();this.confirmAmount.reset('');this.message.set(null);}
  closeConfirm(){this.confirmingForecast.set(null);this.confirmError.set(null);}
  isConfirming(item:RecurrenceForecast){const c=this.confirmingForecast();return !!c&&c.recurrenceId===item.recurrenceId&&c.scheduledDueDate===item.scheduledDueDate;}
  confirmCharge(){const item=this.confirmingForecast();if(!item||this.anticipating())return;if(this.confirmAmount.invalid){this.confirmAmount.markAsTouched();return;}this.anticipating.set(`${item.recurrenceId}:${item.scheduledDueDate}`);this.confirmError.set(null);this.api.confirmForecastCharge(item,this.confirmAmount.value.replace(',','.'),this.confirmKey).pipe(finalize(()=>this.anticipating.set(null))).subscribe({next:r=>{this.confirmingForecast.set(null);this.message.set(`Valor da cobrança de ${item.scheduledDueDate} confirmado em R$ ${r.occurrence.amount}. O lançamento foi criado pendente de quitação na mesma ocorrência.`);this.anticipatedExpenseId.set(r.occurrence.expenseId);this.loadForecasts();},error:(e:HttpErrorResponse)=>{this.confirmError.set((e.error as {message?:string})?.message??'Não foi possível confirmar o valor. O valor digitado foi preservado.');if(e.status===409){this.confirmKey=this.api.newIdempotencyKey();this.loadForecasts();}}});}
  changed(r:RecurrenceChangeResult){this.message.set(r.change.type==='CLOSURE'?`Recorrência ${r.recurrence.description} encerrada. O histórico e os lançamentos até o término foram mantidos.`:`Recorrência ${r.recurrence.description} alterada a partir de ${r.change.effectiveDueDate}.`);this.load(false);this.loadForecasts();}
  refresh(){this.load(false);this.loadForecasts();}
  changeLabel(c:RecurrenceChange){const who=`${c.actorDisplayName} em ${c.occurredAt.slice(0,16).replace('T',' ')}`;return c.type==='CLOSURE'?`Encerrada com último vencimento ${c.effectiveDueDate} por ${who}. Motivo: ${c.reason}`:`Alterada a partir de ${c.effectiveDueDate} (${c.changedFields.map(f=>({description:'descrição',amount:'valor',frequency:'frequência',dueDay:'dia de vencimento',categoryId:'categoria',responsibleUserId:'responsável'} as Record<string,string>)[f]??f).join(', ')}) por ${who}: ${c.updatedCount} atualizado(s), ${c.removedCount} retirado(s), ${c.reviewCount} para revisão.`;}
  reviewLabel(item:RecurrenceForecast){return item.reviewReason==='AFTER_END'?'Revisar: depois do término':item.reviewReason==='OUTSIDE_SCHEDULE'?'Revisar: fora da nova programação':null;}
  forecastLabel(item:RecurrenceForecast){if(item.state==='FORECAST')return item.estimated?'Previsão estimada':'Previsão fixa';return item.expenseStatus==='PAID'?'Lançamento pago':item.expenseStatus==='CANCELLED'?'Lançamento cancelado':item.chargeConfirmed?'Lançamento confirmado':'Lançamento com valor a confirmar';}
  private loadForecasts(){this.forecastLoading.set(true);this.api.forecasts().pipe(finalize(()=>this.forecastLoading.set(false))).subscribe({next:p=>{this.forecasts.set(p.occurrences);this.forecastPeriod.set(`${p.from} a ${p.to}`);},error:e=>this.handle(e,'Não foi possível carregar as previsões.')});}
  private load(clear=true){this.loading.set(true);if(clear)this.error.set(null);this.api.list().pipe(finalize(()=>this.loading.set(false))).subscribe({next:v=>this.recurrences.set(v),error:e=>this.handle(e,'Não foi possível carregar as recorrências.')});}private handle(e:HttpErrorResponse,fallback:string){this.error.set((e.error as {message?:string})?.message??fallback);}
}
