import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';import { MatCardModule } from '@angular/material/card';import { MatFormFieldModule } from '@angular/material/form-field';import { MatInputModule } from '@angular/material/input';
import { finalize } from 'rxjs';import { AccountAccessService, SpaceMember } from '../identity/account-access.service';import { Category, CategoryService } from '../expenses/category.service';import { Recurrence, RecurrenceForecast, RecurrenceFrequency, RecurrenceService, RecurrenceValueType } from './recurrence.service';
@Component({selector:'app-recurrence',imports:[ReactiveFormsModule,RouterLink,MatButtonModule,MatCardModule,MatFormFieldModule,MatInputModule],templateUrl:'./recurrence.component.html',styleUrl:'./recurrence.component.scss'})
export class RecurrenceComponent implements OnInit {
  private readonly fb=inject(FormBuilder);private readonly api=inject(RecurrenceService);private readonly categoriesApi=inject(CategoryService);private readonly identity=inject(AccountAccessService);
  readonly categories=signal<Category[]>([]);readonly members=signal<SpaceMember[]>([]);readonly recurrences=signal<Recurrence[]>([]);readonly forecasts=signal<RecurrenceForecast[]>([]);readonly forecastPeriod=signal('');readonly previewDates=signal<string[]>([]);readonly loading=signal(true);readonly forecastLoading=signal(true);readonly submitting=signal(false);readonly anticipating=signal<string|null>(null);readonly anticipatedExpenseId=signal<string|null>(null);readonly message=signal<string|null>(null);readonly error=signal<string|null>(null);private key=this.api.newIdempotencyKey();
  readonly form=this.fb.nonNullable.group({description:['',[Validators.required,Validators.maxLength(200)]],amount:['',[Validators.required,Validators.pattern(/^\d{1,8}([.,]\d{1,2})?$/)]],valueType:['FIXED' as RecurrenceValueType,Validators.required],frequency:['MONTHLY' as RecurrenceFrequency,Validators.required],firstDueDate:['',Validators.required],lastDueDate:[''],categoryId:[''],responsibleUserId:['']});
  ngOnInit(){this.categoriesApi.list(false).subscribe(v=>this.categories.set(v));this.identity.members().subscribe(v=>this.members.set(v));this.load();this.loadForecasts();}
  preview(){if(this.form.controls.firstDueDate.invalid){this.form.controls.firstDueDate.markAsTouched();return;}const v=this.form.getRawValue();this.api.preview({firstDueDate:v.firstDueDate,lastDueDate:v.lastDueDate||null,frequency:v.frequency}).subscribe({next:d=>{this.previewDates.set(d);this.error.set(null);},error:e=>this.handle(e,'Não foi possível calcular o calendário.')});}
  submit(){if(this.form.invalid||this.submitting()){this.form.markAllAsTouched();return;}const v=this.form.getRawValue();this.submitting.set(true);this.error.set(null);this.api.create({...v,amount:v.amount.replace(',','.'),lastDueDate:v.lastDueDate||null,categoryId:v.categoryId||null,responsibleUserId:v.responsibleUserId||null},this.key).pipe(finalize(()=>this.submitting.set(false))).subscribe({next:r=>{this.message.set('Recorrência cadastrada. Se houver vencimento no mês atual, o lançamento aparecerá em Despesas em até 30 segundos.');this.previewDates.set(r.previewDates);this.key=this.api.newIdempotencyKey();this.form.reset({description:'',amount:'',valueType:'FIXED',frequency:'MONTHLY',firstDueDate:'',lastDueDate:'',categoryId:'',responsibleUserId:''});this.load(false);this.loadForecasts();},error:e=>this.handle(e,'Não foi possível cadastrar a recorrência.')});}
  frequencyLabel(v:RecurrenceFrequency){return {MONTHLY:'Mensal',BIMONTHLY:'Bimestral',QUARTERLY:'Trimestral',SEMIANNUAL:'Semestral',ANNUAL:'Anual'}[v];}valueLabel(v:RecurrenceValueType){return v==='FIXED'?'Valor fixo':'Estimativa variável a confirmar';}
  anticipate(item:RecurrenceForecast){if(this.anticipating()||!window.confirm(`Antecipar o lançamento de ${item.description} com vencimento previsto em ${item.scheduledDueDate}?`))return;const key=this.api.newIdempotencyKey();this.anticipating.set(`${item.recurrenceId}:${item.scheduledDueDate}`);this.error.set(null);this.api.anticipate(item,key).pipe(finalize(()=>this.anticipating.set(null))).subscribe({next:r=>{this.message.set('Lançamento antecipado sem alterar o calendário da recorrência.');this.anticipatedExpenseId.set(r.occurrence.expenseId);this.loadForecasts();},error:e=>this.handle(e,'Não foi possível antecipar o lançamento.')});}
  forecastLabel(item:RecurrenceForecast){if(item.state==='FORECAST')return item.estimated?'Previsão estimada':'Previsão fixa';return item.expenseStatus==='PAID'?'Lançamento pago':item.expenseStatus==='CANCELLED'?'Lançamento cancelado':item.chargeConfirmed?'Lançamento confirmado':'Lançamento com valor a confirmar';}
  private loadForecasts(){this.forecastLoading.set(true);this.api.forecasts().pipe(finalize(()=>this.forecastLoading.set(false))).subscribe({next:p=>{this.forecasts.set(p.occurrences);this.forecastPeriod.set(`${p.from} a ${p.to}`);},error:e=>this.handle(e,'Não foi possível carregar as previsões.')});}
  private load(clear=true){this.loading.set(true);if(clear)this.error.set(null);this.api.list().pipe(finalize(()=>this.loading.set(false))).subscribe({next:v=>this.recurrences.set(v),error:e=>this.handle(e,'Não foi possível carregar as recorrências.')});}private handle(e:HttpErrorResponse,fallback:string){this.error.set((e.error as {message?:string})?.message??fallback);}
}
