package com.malyah.accountmanager.notifications.infrastructure;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.sql.Timestamp;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

import com.malyah.accountmanager.expenses.application.CancelExpenseCommand;
import com.malyah.accountmanager.expenses.application.CorrectExpenseCommand;
import com.malyah.accountmanager.expenses.application.CreateOneOffExpenseCommand;
import com.malyah.accountmanager.expenses.application.ExpenseService;
import com.malyah.accountmanager.expenses.application.ReversePaymentCommand;
import com.malyah.accountmanager.expenses.application.SettleExpenseCommand;
import com.malyah.accountmanager.expenses.domain.ExpenseStatus;
import com.malyah.accountmanager.expenses.infrastructure.JdbcCategoryRepository;
import com.malyah.accountmanager.expenses.infrastructure.JdbcExpenseReminderQueries;
import com.malyah.accountmanager.expenses.infrastructure.JdbcExpenseRepository;
import com.malyah.accountmanager.expenses.infrastructure.JdbcInstallmentExpenses;
import com.malyah.accountmanager.expenses.infrastructure.JdbcRecurringExpenseMaterializer;
import com.malyah.accountmanager.identity.application.AuthenticatedUserContext;
import com.malyah.accountmanager.identity.application.AuthenticatedUserContextService;
import com.malyah.accountmanager.identity.application.port.AuthenticatedUserContextRepository;
import com.malyah.accountmanager.identity.domain.SpaceRole;
import com.malyah.accountmanager.identity.infrastructure.JdbcFinancialMemberAccess;
import com.malyah.accountmanager.installments.application.InstallmentPurchaseCommand;
import com.malyah.accountmanager.installments.application.InstallmentPurchaseService;
import com.malyah.accountmanager.installments.infrastructure.InstallmentTestFixtures;
import com.malyah.accountmanager.notifications.application.ReminderQueryValidationException;
import com.malyah.accountmanager.notifications.application.ReminderSettingsCommand;
import com.malyah.accountmanager.notifications.application.ReminderSettingsService;
import com.malyah.accountmanager.notifications.application.ReminderSettingsUseCase;
import com.malyah.accountmanager.notifications.application.ReminderSummaryNotFoundException;
import com.malyah.accountmanager.notifications.application.ReminderSummaryService;
import com.malyah.accountmanager.notifications.application.ReminderSummaryUseCase;
import com.malyah.accountmanager.notifications.application.ReminderSummaryView;
import com.malyah.accountmanager.notifications.application.port.WhatsAppProviderStatus;
import com.malyah.accountmanager.recurrences.application.CreateRecurrenceCommand;
import com.malyah.accountmanager.recurrences.application.RecurrenceForecastCatalog;
import com.malyah.accountmanager.recurrences.application.RecurrenceService;
import com.malyah.accountmanager.recurrences.domain.RecurrenceFrequency;
import com.malyah.accountmanager.recurrences.domain.RecurrenceValueType;
import com.malyah.accountmanager.recurrences.infrastructure.JdbcRecurrenceGenerationJob;
import com.malyah.accountmanager.recurrences.infrastructure.RecurrenceTestFixtures;

/**
 * H08.2 against real PostgreSQL: bills created, paid, reverted, cancelled and corrected through their own use cases,
 * recurrences generated by the H04.2 queue, and the reminder job driven by a controllable clock. Every expected value
 * comes from the matrix E1–E16 in docs/evidencias/H08.2.md. "Today" is 05/10/2026 in São Paulo (UTC-3): the first
 * slot is 12:00 UTC and the second 21:00 UTC.
 */
@Testcontainers
class ReminderSummaryPostgresIT {
    static final Instant FIRST = Instant.parse("2026-10-05T12:00:00Z");
    static final Instant SECOND = Instant.parse("2026-10-05T21:00:00Z");
    static final Instant NEXT_FIRST = Instant.parse("2026-10-06T12:00:00Z");
    static final UUID SPACE = UUID.fromString("c0000000-0000-0000-0000-000000000001");
    static final UUID OTHER = UUID.fromString("d0000000-0000-0000-0000-000000000001");
    static final UUID ADMIN = UUID.fromString("c0000000-0000-0000-0000-000000000002");
    static final UUID GUEST = UUID.fromString("c0000000-0000-0000-0000-000000000003");
    static final UUID OUTSIDER = UUID.fromString("d0000000-0000-0000-0000-000000000002");
    static final String A = "admin@example.com";
    static final String G = "guest@example.com";
    static final String O = "other@example.com";

    @Container
    static final PostgreSQLContainer POSTGRES = new PostgreSQLContainer("postgres:17.6-alpine")
            .withDatabaseName("account_manager_reminders_test").withUsername("account_manager")
            .withPassword("test-only-password");

    private JdbcTemplate jdbc;
    private TransactionTemplate tx;
    private MutableClock clock;
    private AuthenticatedUserContextService context;
    private JdbcFinancialMemberAccess members;
    private JdbcCategoryRepository categories;
    private ExpenseService expenses;
    private RecurrenceService recurrences;
    private InstallmentPurchaseService installments;
    private JdbcRecurrenceGenerationJob generation;
    private ReminderSettingsUseCase settings;
    private boolean providerAvailable;
    private ReminderSummaryService service;
    private ReminderSummaryJob job;
    private ReminderSummaryUseCase reads;

    @BeforeEach
    void reset() {
        var dataSource = new DriverManagerDataSource(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(),
                POSTGRES.getPassword());
        var flyway = Flyway.configure().dataSource(dataSource).cleanDisabled(false).load();
        flyway.clean();
        assertThat(flyway.migrate().migrationsExecuted).isEqualTo(27);
        jdbc = new JdbcTemplate(dataSource);
        tx = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        insertSpace(SPACE, "Casa");
        insertSpace(OTHER, "Outra");
        insertUser(ADMIN, "Admin", A, SPACE, "ADMINISTRATOR");
        insertUser(GUEST, "Convidado", G, SPACE, "GUEST");
        insertUser(OUTSIDER, "Outro", O, OTHER, "ADMINISTRATOR");
        clock = new MutableClock(FIRST);
        context = new AuthenticatedUserContextService(contextRepository());
        members = new JdbcFinancialMemberAccess(jdbc);
        categories = new JdbcCategoryRepository(jdbc);
        expenses = new ExpenseService(new JdbcExpenseRepository(jdbc), context, UUID::randomUUID, clock, members,
                categories);
        var materializer = new JdbcRecurringExpenseMaterializer(jdbc, tx);
        recurrences = RecurrenceTestFixtures.service(jdbc, context, categories, members, clock, materializer,
                (email, command) -> expenses.confirmCharge(email, command));
        installments = InstallmentTestFixtures.purchases(jdbc, new JdbcInstallmentExpenses(jdbc, UUID::randomUUID),
                context, categories, members, clock);
        generation = new JdbcRecurrenceGenerationJob(jdbc, tx, materializer, clock, Duration.ofMinutes(2), 25);
        WhatsAppProviderStatus provider = () -> providerAvailable
                ? new WhatsAppProviderStatus.Availability(true, "TEST_PROVIDER", "Porta de teste.")
                : new MetaWhatsAppProvider(MetaWhatsAppProperties.disabled()).availability();
        settings = new TransactionalReminderSettingsUseCase(new ReminderSettingsService(
                new JdbcReminderSettingsRepository(jdbc), context, members, provider, clock, UUID::randomUUID), tx);
        service = new ReminderSummaryService(new JdbcReminderSummaryRepository(jdbc),
                new JdbcMemberNotificationRepository(jdbc), new JdbcReminderSettingsRepository(jdbc), new JdbcExpenseReminderQueries(jdbc),
                new RecurrenceForecastCatalog(RecurrenceTestFixtures.service(jdbc, context, categories, members,
                        clock, materializer, null)), generation, provider, context, clock, UUID::randomUUID,
                "https://contas.malyah.tech");
        job = new ReminderSummaryJob(service, tx, clock);
        reads = new TransactionalReminderSummaryUseCase(service, tx);
    }

    /** E1: -6 nowhere; -5 and -2 in the first; -1 and 0 in both; +1 (overdue) in the first only. */
    @Test
    void e1CalendarByDistance() {
        pending("Seis", "6.00", d(10, 11));
        pending("Cinco", "5.00", d(10, 10));
        pending("Dois", "2.00", d(10, 7));
        pending("Um", "1.00", d(10, 6));
        pending("Hoje", "10.00", d(10, 5));
        pending("Ontem", "20.00", d(10, 4));
        at(FIRST);
        var first = only(d(10, 5), "FIRST");
        assertThat(labels(first)).containsExactly("Ontem", "Hoje", "Um", "Dois", "Cinco");
        assertThat(first.count()).isEqualTo(5);
        assertThat(first.total()).isEqualTo("38.00");
        assertThat(first.overdueCount()).isEqualTo(1);
        assertThat(first.items().getFirst().overdue()).isTrue();
        at(SECOND);
        var second = only(d(10, 5), "SECOND");
        assertThat(labels(second)).containsExactly("Hoje", "Um");
        assertThat(second.total()).isEqualTo("11.00");
        assertThat(runs()).containsExactly("2026-10-05 FIRST GENERATED", "2026-10-05 SECOND GENERATED");
    }

    /** E2: at 23:30 local (02:30 UTC of the next day) the local date is still 05/10. */
    @Test
    void e2DayTurnUsesTheSpaceZone() {
        pending("Um", "1.00", d(10, 6));
        pending("Hoje", "10.00", d(10, 5));
        at(Instant.parse("2026-10-06T02:30:00Z"));
        assertThat(reads.preview(A, null, "SECOND").today()).isEqualTo(d(10, 5));
        assertThat(runs()).containsExactly("2026-10-05 FIRST MISSED", "2026-10-05 SECOND MISSED");
        assertThat(count("reminder_summaries")).isZero();
        at(NEXT_FIRST);
        var first = only(d(10, 6), "FIRST");
        assertThat(labels(first)).containsExactly("Hoje", "Um");
        assertThat(first.overdueCount()).isEqualTo(1);
    }

    /** E3: paid and cancelled never appear; a reverted payment is back in the next applicable slot. */
    @Test
    void e3PaidCancelledAndReverted() {
        var dois = pending("Dois", "2.00", d(10, 7));
        var um = pending("Um", "1.00", d(10, 6));
        pending("Hoje", "10.00", d(10, 5));
        settle(dois);
        cancel(um);
        at(FIRST);
        assertThat(labels(only(d(10, 5), "FIRST"))).containsExactly("Hoje");
        clock.set(Instant.parse("2026-10-05T13:00:00Z"));
        tx.execute(s -> expenses.reversePayment(A, new ReversePaymentCommand(dois, expenses.get(A, dois).version(),
                "Pagamento lançado por engano", UUID.randomUUID())));
        at(SECOND);
        assertThat(labels(only(d(10, 5), "SECOND"))).containsExactly("Hoje");
        at(NEXT_FIRST);
        assertThat(labels(only(d(10, 6), "FIRST"))).containsExactly("Hoje", "Dois");
    }

    /** E4: a processed slot is not redone; the new due date counts from the next slot. */
    @Test
    void e4DueDateChange() {
        var longe = pending("Longe", "30.00", d(10, 20));
        var um = pending("Um", "1.00", d(10, 6));
        at(FIRST);
        assertThat(labels(only(d(10, 5), "FIRST"))).containsExactly("Um");
        clock.set(Instant.parse("2026-10-05T12:20:00Z"));
        correctDue(longe, d(10, 6));
        correctDue(um, d(10, 20));
        at(Instant.parse("2026-10-05T12:30:00Z"));
        assertThat(count("reminder_summaries")).isOne();
        assertThat(labels(only(d(10, 5), "FIRST"))).containsExactly("Um");
        at(SECOND);
        assertThat(labels(only(d(10, 5), "SECOND"))).containsExactly("Longe");
    }

    /** E5 + E6: a variable recurrence due in the window is materialized ahead of time and flagged as estimate. */
    @Test
    void e5EstimatesAndEarlyMaterialization() {
        clock.set(Instant.parse("2026-10-05T11:00:00Z"));
        recurrence("Luz", "90.00", RecurrenceValueType.VARIABLE_ESTIMATE, d(10, 7));
        pending("Pão", "10.00", d(10, 7));
        assertThat(count("expense_entries")).isOne();
        at(FIRST);
        var first = only(d(10, 5), "FIRST");
        assertThat(first.items()).extracting(i -> i.label() + " " + i.estimated() + " " + i.forecast() + " " + i.origin())
                .containsExactly("Luz true false RECURRENCE", "Pão false false ONE_OFF");
        assertThat(first.items().getFirst().expenseId()).isNotNull();
        assertThat(first.total()).isEqualTo("100.00");
        assertThat(first.estimatedCount()).isEqualTo(1);
        assertThat(first.estimatedTotal()).isEqualTo("90.00");
        assertThat(first.text()).contains("(1 estimada: R$ 90,00)").contains("Luz — R$ 90,00 (estimada)");
        assertThat(count("expense_entries")).isEqualTo(2);
    }

    /** E6: due 03/10 materialized on 28/09 by the first slot; the periodic generation never duplicates it. */
    @Test
    void e6NextMonthOccurrenceIsMaterializedByTheFirstReminder() {
        clock.set(Instant.parse("2026-09-28T11:00:00Z"));
        var internet = recurrence("Internet", "120.00", RecurrenceValueType.FIXED, d(10, 3));
        generation.poll();
        assertThat(count("expense_entries")).isZero();
        at(Instant.parse("2026-09-28T12:00:00Z"));
        var first = only(LocalDate.of(2026, 9, 28), "FIRST");
        assertThat(labels(first)).containsExactly("Internet");
        var expense = jdbc.queryForObject("select expense_id from recurrence_occurrences where recurrence_id = ?",
                UUID.class, internet);
        assertThat(first.items().getFirst().expenseId()).isEqualTo(expense);
        assertThat(first.items().getFirst().forecast()).isFalse();
        at(Instant.parse("2026-10-01T12:00:00Z"));
        generation.poll();
        at(Instant.parse("2026-10-02T12:00:00Z"));
        assertThat(only(d(10, 2), "FIRST").items().getFirst().expenseId()).isEqualTo(expense);
        assertThat(count("expense_entries")).isOne();
        assertThat(count("recurrence_occurrences")).isOne();
    }

    /** E6: when the generation cannot run, the occurrence still appears once, as a forecast. */
    @Test
    void e6WithoutGenerationTheOccurrenceIsAForecastAndPreviewNeverMaterializes() {
        clock.set(Instant.parse("2026-09-28T11:00:00Z"));
        var internet = recurrence("Internet", "120.00", RecurrenceValueType.FIXED, d(10, 3));
        clock.set(Instant.parse("2026-09-28T12:00:00Z"));
        var preview = reads.preview(G, null, "FIRST").summary();
        assertThat(preview.items()).singleElement().satisfies(item -> {
            assertThat(item.forecast()).isTrue();
            assertThat(item.recurrenceId()).isEqualTo(internet);
            assertThat(item.origin()).isEqualTo("RECURRENCE_FORECAST");
        });
        assertThat(count("expense_entries")).isZero();
        var withoutGeneration = new ReminderSummaryJob(new ReminderSummaryService(new JdbcReminderSummaryRepository(jdbc),
                new JdbcMemberNotificationRepository(jdbc), new JdbcReminderSettingsRepository(jdbc), new JdbcExpenseReminderQueries(jdbc),
                new RecurrenceForecastCatalog(RecurrenceTestFixtures.service(jdbc, context, categories, members, clock,
                        new JdbcRecurringExpenseMaterializer(jdbc, tx), null)),
                (space, through) -> { throw new IllegalStateException("generation down"); },
                new MetaWhatsAppProvider(MetaWhatsAppProperties.disabled()), context, clock, UUID::randomUUID, "https://x"), tx, clock);
        withoutGeneration.poll();
        var stored = only(LocalDate.of(2026, 9, 28), "FIRST");
        assertThat(stored.items()).singleElement().extracting(ReminderSummaryView.Item::forecast).isEqualTo(true);
        assertThat(jdbc.queryForObject("select scheduled_due_date from reminder_summary_items", LocalDate.class))
                .isEqualTo(d(10, 3));
    }

    /** E7: the reminder slot and the generation racing for the same occurrence create one expense. */
    @Test
    void e7ConcurrentGeneration() throws Exception {
        clock.set(Instant.parse("2026-09-28T11:00:00Z"));
        recurrence("Internet", "120.00", RecurrenceValueType.FIXED, d(10, 3));
        clock.set(Instant.parse("2026-09-28T12:00:00Z"));
        race(() -> { job.poll(); return null; }, () -> { generation.materializeUpcoming(SPACE, d(10, 3)); return null; },
                () -> { job.poll(); return null; });
        assertThat(count("expense_entries")).isOne();
        assertThat(count("recurrence_occurrences")).isOne();
        assertThat(count("reminder_summaries")).isOne();
        assertThat(count("reminder_summary_items")).isOne();
    }

    /** E8: a parcel is an item of its own, n/N, without the purchase or the other parcels. */
    @Test
    void e8Installments() {
        clock.set(Instant.parse("2026-10-05T11:00:00Z"));
        var purchase = tx.execute(s -> installments.create(A, new InstallmentPurchaseCommand("Geladeira", "3000.00", 10,
                d(8, 7), null, null, UUID.randomUUID())).purchase());
        settle(purchase.installments().get(0).expenseId());
        settle(purchase.installments().get(1).expenseId());
        at(FIRST);
        var first = only(d(10, 5), "FIRST");
        assertThat(first.items()).singleElement().satisfies(item -> {
            assertThat(item.label()).isEqualTo("Geladeira (3/10)");
            assertThat(item.installmentNumber()).isEqualTo(3);
            assertThat(item.installmentCount()).isEqualTo(10);
            assertThat(item.amount()).isEqualTo("300.00");
            assertThat(item.origin()).isEqualTo("INSTALLMENT");
        });
    }

    /** E9 + E10: nothing eligible records EMPTY; seven bills keep five details and total all seven exactly. */
    @Test
    void e9e10EmptyOneAndMoreThanFive() {
        pending("Longe", "1.00", d(10, 20));
        at(FIRST);
        assertThat(runs()).containsExactly("2026-10-05 FIRST EMPTY");
        assertThat(count("reminder_summaries")).isZero();
        pending("Única", "0.10", d(10, 5));
        at(SECOND);
        assertThat(only(d(10, 5), "SECOND").count()).isOne();
        var amounts = List.of("0.20", "1234.56", "99.99", "0.01", "10.00", "5.05");
        for (int i = 0; i < amounts.size(); i++) pending("Conta " + i, amounts.get(i), d(10, 6 + i % 3));
        at(NEXT_FIRST);
        var seven = only(d(10, 6), "FIRST");
        assertThat(seven.count()).isEqualTo(7);
        assertThat(seven.detailCount()).isEqualTo(5);
        assertThat(seven.remaining()).isEqualTo(2);
        assertThat(seven.items()).hasSize(7);
        assertThat(seven.total()).isEqualTo("1349.91");
        assertThat(seven.text()).contains("7 contas, total R$ 1.349,91").contains("e mais 2 contas");
        assertThat(jdbc.queryForObject("select total_amount::text from reminder_summaries where local_date = ?",
                String.class, d(10, 6))).isEqualTo("1349.91");
    }

    /** E11: overdue first by date, then the nearest due date, ties by description ignoring case. */
    @Test
    void e11PriorityAndTies() {
        pending("gama", "1.00", d(10, 7));
        pending("beta", "1.00", d(10, 7));
        pending("Alfa", "1.00", d(10, 7));
        pending("Recente", "1.00", d(10, 3));
        pending("Antiga", "1.00", d(10, 1));
        at(FIRST);
        assertThat(labels(only(d(10, 5), "FIRST"))).containsExactly("Antiga", "Recente", "Alfa", "beta", "gama");
        assertThat(jdbc.queryForList("select description from reminder_summary_items order by position", String.class))
                .containsExactly("Antiga", "Recente", "Alfa", "beta", "gama");
    }

    /** E12: 08:30/20:00; a slot not processed within its hour is missed without a late summary. */
    @Test
    void e12CustomScheduleAndMissedWindow() {
        pending("Hoje", "10.00", d(10, 5));
        pending("Amanhã", "5.00", d(10, 6));
        clock.set(Instant.parse("2026-10-05T11:00:00Z"));
        tx.execute(s -> settings.changeSchedule(A, ReminderSettingsCommand.schedule(0L, "08:30", "20:00", UUID.randomUUID())));
        at(Instant.parse("2026-10-05T11:29:00Z"));
        assertThat(runs()).isEmpty();
        at(Instant.parse("2026-10-05T11:30:00Z"));
        var first = only(d(10, 5), "FIRST");
        assertThat(first.scheduledTime()).isEqualTo("08:30");
        at(Instant.parse("2026-10-05T22:59:00Z"));
        assertThat(runs()).containsExactly("2026-10-05 FIRST GENERATED");
        at(Instant.parse("2026-10-05T23:00:00Z"));
        assertThat(only(d(10, 5), "SECOND").scheduledTime()).isEqualTo("20:00");
        at(Instant.parse("2026-10-06T12:31:00Z"));
        assertThat(runs()).contains("2026-10-06 FIRST MISSED");
        assertThat(jdbc.queryForObject("select count(*) from reminder_summaries where local_date = ?", Long.class,
                d(10, 6))).isZero();
    }

    /** E13: the in-app summary always exists; WhatsApp is planned only for a ready channel of the administrator. */
    @Test
    void e13WhatsAppStatesNeverBlockTheSummary() {
        pending("Amanhã", "5.00", d(10, 6));
        at(FIRST);
        assertThat(channels(d(10, 5), "FIRST")).containsExactly("IN_APP PLANNED null null", "WHATSAPP SKIPPED RECIPIENT_REQUIRED null");
        clock.set(Instant.parse("2026-10-05T13:00:00Z"));
        tx.execute(s -> settings.changeRecipient(A, ReminderSettingsCommand.recipient(0L, "(11) 98765-4321", UUID.randomUUID())));
        tx.execute(s -> settings.grantConsent(A, ReminderSettingsCommand.consent(1L, "(11) 98765-4321", true, UUID.randomUUID())));
        at(SECOND);
        assertThat(channels(d(10, 5), "SECOND")).containsExactly("IN_APP PLANNED null null", "WHATSAPP SKIPPED DISABLED null");
        clock.set(Instant.parse("2026-10-06T11:00:00Z"));
        tx.execute(s -> settings.changeChannel(A, ReminderSettingsCommand.channel(2L, true, UUID.randomUUID())));
        at(NEXT_FIRST);
        assertThat(channels(d(10, 6), "FIRST")).containsExactly("IN_APP PLANNED null null", "WHATSAPP SKIPPED PROVIDER_UNAVAILABLE null");
        providerAvailable = true;
        at(Instant.parse("2026-10-06T21:00:00Z"));
        assertThat(channels(d(10, 6), "SECOND")).containsExactly("IN_APP PLANNED null null", "WHATSAPP PLANNED null " + ADMIN);
        assertThat(jdbc.queryForObject("select count(*) from reminder_summary_channels where recipient_user_id = ?",
                Long.class, GUEST)).isZero();
    }

    /** E14: the same slot processed again and by concurrent workers is recorded once. */
    @Test
    void e14ReexecutionAndConcurrency() throws Exception {
        pending("Hoje", "10.00", d(10, 5));
        clock.set(FIRST);
        race(() -> { job.poll(); return null; }, () -> { job.poll(); return null; }, () -> { job.poll(); return null; });
        job.poll();
        var task = tx.execute(s -> service.dueSlots(FIRST));
        assertThat(task).isEmpty();
        assertThat(runs()).containsExactly("2026-10-05 FIRST GENERATED");
        assertThat(count("reminder_summaries")).isOne();
        assertThat(count("reminder_summary_items")).isOne();
        assertThat(count("reminder_summary_channels")).isEqualTo(2);
    }

    /** E15: each space only sees its own bills and summaries. */
    @Test
    void e15Isolation() {
        pending("Nossa", "10.00", d(10, 5));
        tx.execute(s -> expenses.create(O, new CreateOneOffExpenseCommand("Deles", "99.00", ExpenseStatus.PENDING,
                d(10, 5), null, null, UUID.randomUUID(), null, null, null, null, null)));
        at(FIRST);
        assertThat(labels(only(d(10, 5), "FIRST"))).containsExactly("Nossa");
        var theirs = jdbc.queryForObject("select id from reminder_summaries where space_id = ?", UUID.class, OTHER);
        assertThat(labels(reads.summary(O, theirs))).containsExactly("Deles");
        assertThatThrownBy(() -> reads.summary(A, theirs)).isInstanceOf(ReminderSummaryNotFoundException.class);
        assertThatThrownBy(() -> reads.summary(G, theirs)).isInstanceOf(ReminderSummaryNotFoundException.class);
        assertThat(reads.preview(O, null, "FIRST").summary().items()).extracting(ReminderSummaryView.Item::label)
                .containsExactly("Deles");
    }

    /** E16: both members read the simulation and the summary; invalid queries are refused; nothing is written. */
    @Test
    void e16PreviewAndLinkForBothMembers() {
        pending("Hoje", "10.00", d(10, 5));
        pending("Cinco", "5.00", d(10, 10));
        clock.set(Instant.parse("2026-10-05T15:00:00Z"));
        var admin = reads.preview(A, "2026-10-05", "FIRST");
        var guest = reads.preview(G, "2026-10-05", "FIRST");
        assertThat(labels(admin.summary())).containsExactly("Hoje", "Cinco");
        assertThat(guest).isEqualTo(admin);
        assertThat(labels(reads.preview(G, "2026-10-05", "SECOND").summary())).containsExactly("Hoje");
        assertThat(labels(reads.preview(G, "2026-10-08", "FIRST").summary())).containsExactly("Hoje", "Cinco");
        assertThat(reads.preview(G, "2026-10-08", "FIRST").summary().overdueCount()).isOne();
        assertThat(reads.preview(G, "2026-10-12", "SECOND").summary()).isNull();
        assertThat(count("reminder_slot_runs") + count("reminder_summaries")).isZero();
        for (var invalid : List.of(new String[] {"2026-10-04", "FIRST"}, new String[] {"2026-12-05", "FIRST"},
                new String[] {"amanhã", "FIRST"}, new String[] {"2026-10-05", "THIRD"}))
            assertThatThrownBy(() -> reads.preview(G, invalid[0], invalid[1]))
                    .isInstanceOf(ReminderQueryValidationException.class);
        at(Instant.parse("2026-10-05T21:00:00Z"));
        var id = jdbc.queryForObject("select id from reminder_summaries", UUID.class);
        var byGuest = reads.summary(G, id);
        assertThat(byGuest).isEqualTo(reads.summary(A, id));
        assertThat(byGuest.link()).isEqualTo("https://contas.malyah.tech/lembretes/resumos/" + id);
        assertThat(byGuest.text()).endsWith("Lista completa: " + byGuest.link());
    }

    private void at(Instant instant) {
        clock.set(instant);
        job.poll();
    }

    private ReminderSummaryView only(LocalDate date, String slot) {
        var id = jdbc.queryForObject("select id from reminder_summaries where space_id = ? and local_date = ? and slot = ?",
                UUID.class, SPACE, date, slot);
        return reads.summary(A, id);
    }

    private List<String> channels(LocalDate date, String slot) {
        return jdbc.query("""
                select c.channel, c.status, c.skip_reason, c.recipient_user_id from reminder_summary_channels c
                  join reminder_summaries s on s.id = c.summary_id
                 where s.space_id = ? and s.local_date = ? and s.slot = ? order by c.channel
                """, (rs, row) -> rs.getString(1) + " " + rs.getString(2) + " " + rs.getString(3) + " "
                + rs.getString(4), SPACE, date, slot);
    }

    private List<String> runs() {
        return jdbc.query("select local_date, slot, outcome from reminder_slot_runs where space_id = ? order by 1, 2",
                (rs, row) -> rs.getObject(1, LocalDate.class) + " " + rs.getString(2) + " " + rs.getString(3), SPACE);
    }

    private static List<String> labels(ReminderSummaryView view) {
        return view.items().stream().map(ReminderSummaryView.Item::label).toList();
    }

    private long count(String table) {
        return jdbc.queryForObject("select count(*) from " + table, Long.class);
    }

    private UUID pending(String description, String amount, LocalDate due) {
        return tx.execute(s -> expenses.create(A, new CreateOneOffExpenseCommand(description, amount,
                ExpenseStatus.PENDING, due, null, null, UUID.randomUUID(), null, null, null, null, null))
                .expense().id());
    }

    private void settle(UUID id) {
        var current = expenses.get(A, id);
        tx.execute(s -> expenses.settle(A, new SettleExpenseCommand(id, current.version(), current.amount(),
                d(10, 1), ADMIN, null, UUID.randomUUID())));
    }

    private void cancel(UUID id) {
        tx.execute(s -> expenses.cancel(A, new CancelExpenseCommand(id, expenses.get(A, id).version(), "Não será cobrada",
                UUID.randomUUID())));
    }

    private void correctDue(UUID id, LocalDate due) {
        var e = expenses.get(A, id);
        tx.execute(s -> expenses.correct(A, new CorrectExpenseCommand(id, e.version(), e.status(), e.description(),
                e.amount(), due, e.notes(), null, null, null, null, UUID.randomUUID(), e.categoryId(),
                e.responsibleUserId())));
    }

    private UUID recurrence(String description, String amount, RecurrenceValueType type, LocalDate first) {
        return tx.execute(s -> recurrences.create(A, new CreateRecurrenceCommand(description, amount, type,
                RecurrenceFrequency.MONTHLY, first, null, null, null, UUID.randomUUID())).recurrence().id());
    }

    @SafeVarargs
    private static void race(Callable<Void>... tasks) throws Exception {
        var start = new CountDownLatch(1);
        try (var pool = Executors.newFixedThreadPool(tasks.length)) {
            var futures = java.util.Arrays.stream(tasks).map(task -> pool.submit(() -> {
                start.await();
                return task.call();
            })).toList();
            start.countDown();
            for (var future : futures) future.get();
        }
    }

    private static LocalDate d(int month, int day) {
        return LocalDate.of(2026, month, day);
    }

    private AuthenticatedUserContextRepository contextRepository() {
        return email -> jdbc.query("""
                select u.id, u.display_name, u.normalized_email, s.id, s.name, m.role, s.currency_code, s.locale,
                       s.time_zone
                  from identity_users u
                  join space_memberships m on m.user_id = u.id and m.active = true
                  join family_spaces s on s.id = m.space_id
                 where u.normalized_email = ?
                """, (rs, row) -> new AuthenticatedUserContext(rs.getObject(1, UUID.class), rs.getString(2),
                rs.getString(3), rs.getObject(4, UUID.class), rs.getString(5), SpaceRole.valueOf(rs.getString(6)),
                rs.getString(7), rs.getString(8), rs.getString(9)), email).stream().findFirst();
    }

    private void insertSpace(UUID id, String name) {
        jdbc.update("insert into family_spaces(id,name,currency_code,locale,time_zone,created_at) values "
                + "(?,?,'BRL','pt-BR','America/Sao_Paulo',?)", id, name, Timestamp.from(FIRST.minusSeconds(864000)));
    }

    private void insertUser(UUID id, String name, String email, UUID space, String role) {
        jdbc.update("insert into identity_users(id,display_name,normalized_email,password_hash,email_confirmed,"
                + "created_at) values (?,?,?,'{test}x',true,?)", id, name, email, Timestamp.from(FIRST.minusSeconds(864000)));
        jdbc.update("insert into space_memberships(id,user_id,space_id,role,active,created_at) values "
                + "(?,?,?,?,true,?)", UUID.randomUUID(), id, space, role, Timestamp.from(FIRST.minusSeconds(864000)));
    }

    static final class MutableClock extends Clock {
        private volatile Instant now;

        MutableClock(Instant now) {
            this.now = now;
        }

        void set(Instant instant) {
            now = instant;
        }

        @Override
        public ZoneId getZone() {
            return ZoneOffset.UTC;
        }

        @Override
        public Clock withZone(ZoneId zone) {
            return this;
        }

        @Override
        public Instant instant() {
            return now;
        }
    }
}
