package com.malyah.accountmanager.reporting.infrastructure;

import static com.malyah.accountmanager.reporting.infrastructure.MonthClosingPostgresIT.assertOctober;
import static com.malyah.accountmanager.reporting.infrastructure.MonthClosingPostgresIT.line;
import static com.malyah.accountmanager.reporting.infrastructure.MonthClosingPostgresIT.outcome;
import static com.malyah.accountmanager.reporting.infrastructure.MonthClosingPostgresIT.race;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.groups.Tuple.tuple;

import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.jupiter.api.Test;

import com.malyah.accountmanager.expenses.infrastructure.JdbcExpenseReportQueries;
import com.malyah.accountmanager.reporting.application.CloseMonthResult;
import com.malyah.accountmanager.reporting.application.ClosingIdempotencyConflictException;
import com.malyah.accountmanager.reporting.application.ClosingPendingConfirmationRequiredException;
import com.malyah.accountmanager.reporting.application.ClosingSnapshotView;
import com.malyah.accountmanager.reporting.application.ClosingVersionConflictException;
import com.malyah.accountmanager.reporting.application.ClosingVersionListView;
import com.malyah.accountmanager.reporting.application.ClosingVersionNotFoundException;
import com.malyah.accountmanager.reporting.application.GenerateVersionCommand;
import com.malyah.accountmanager.reporting.application.MonthAlreadyClosedException;
import com.malyah.accountmanager.reporting.application.MonthClosingListView;
import com.malyah.accountmanager.reporting.application.MonthClosingUseCase;
import com.malyah.accountmanager.reporting.application.MonthNotClosedException;
import com.malyah.accountmanager.reporting.application.ReportQueryValidationException;

/**
 * H07.3 against real PostgreSQL: matrix V1–V13 of docs/evidencias/H07.3.md. October is closed by the guest on
 * 15/10/2026 12:00 in São Paulo (version 1 = C1); unless stated, a new version is generated by the administrator on
 * 16/10/2026 10:00 in São Paulo. Expected values were computed by hand before the implementation.
 */
class MonthClosingVersionsPostgresIT extends MonthClosingTestSupport {
    static final Instant LATER = Instant.parse("2026-10-16T13:00:00Z");
    static final LocalDate OCT_15 = LocalDate.of(2026, 10, 15);

    @Test
    void v1AMemberGeneratesTheNextVersionFromTheCurrentData() {
        var data = matrix();
        close(G, "2026-10", true);
        settle(data.o2, "100.00", OCT_15, GUEST);
        assertThat(view(A, "2026-10").status()).isEqualTo("OUTDATED");

        var result = generate(at(LATER), A, 1, true, UUID.randomUUID());

        assertThat(result.replayed()).isFalse();
        var v2 = result.closing().saved();
        assertThat(v2.version()).isEqualTo(2);
        assertThat(v2.authorUserId()).isEqualTo(ADMIN);
        assertThat(v2.authorDisplayName()).isEqualTo("Admin");
        assertThat(v2.closedAt()).isEqualTo(LATER);
        assertThat(v2.businessDate()).isEqualTo(LocalDate.of(2026, 10, 16));
        assertThat(v2.pendingAcknowledged()).isTrue();
        assertTotals(v2, 8, "2792.33", "180.00", 5, "1062.33", 3, "1740.00", "180.00", 2, "1560.00");
        assertThat(v2.indicators().adjustmentIncrease()).isEqualTo("20.00");
        assertThat(v2.indicators().adjustmentDiscount()).isEqualTo("10.00");
        assertThat(line(v2, data.o2).status()).isEqualTo("PAID");
        assertThat(result.closing().status()).isEqualTo("UP_TO_DATE");
        assertThat(result.closing().changes()).isEmpty();
        assertThat(jdbc.queryForObject("select current_version from month_closings", Integer.class)).isEqualTo(2);
        assertThat(jdbc.queryForList("""
                select version_number, event_type, actor_user_id from month_closing_events order by version_number
                """)).extracting(row -> tuple(row.get("version_number"), row.get("event_type"),
                row.get("actor_user_id"))).containsExactly(tuple(1, "MONTH_CLOSED", GUEST),
                tuple(2, "VERSION_GENERATED", ADMIN));
        assertThat(view(G, "2026-10").saved()).isEqualTo(v2);
    }

    @Test
    void v2EveryVersionCanBeListedAndReadAsItWasSaved() {
        var data = matrix();
        var v1 = close(G, "2026-10", true).closing().saved();
        settle(data.o2, "100.00", OCT_15, GUEST);
        var v2 = generate(at(LATER), A, 1, true, UUID.randomUUID()).closing().saved();

        var list = closings.versions(G, "2026-10");
        assertThat(list.month()).isEqualTo("2026-10");
        assertThat(list.currentVersion()).isEqualTo(2);
        assertThat(list.versions()).extracting(ClosingVersionListView.Item::version,
                ClosingVersionListView.Item::authorDisplayName, ClosingVersionListView.Item::closedAt,
                item -> item.indicators().pendingTotal(), ClosingVersionListView.Item::current)
                .containsExactly(tuple(1, "Convidado", NOW, "1840.00", false),
                        tuple(2, "Admin", LATER, "1740.00", true));
        var first = closings.version(A, "2026-10", "1");
        assertThat(first.current()).isFalse();
        assertThat(first.currentVersion()).isEqualTo(2);
        assertThat(first.snapshot()).isEqualTo(v1);
        assertOctober(first.snapshot());
        assertThat(line(first.snapshot(), data.o2).status()).isEqualTo("PENDING");
        var second = closings.version(A, "2026-10", "2");
        assertThat(second.current()).isTrue();
        assertThat(second.snapshot()).isEqualTo(v2);
    }

    @Test
    void v3PendingEntriesStillNeedTheConfirmedWarning() {
        var data = matrix();
        close(G, "2026-10", true);
        settle(data.o2, "100.00", OCT_15, GUEST);
        var rows = closingRows();
        assertThatThrownBy(() -> generate(at(LATER), A, 1, false, UUID.randomUUID()))
                .isInstanceOfSatisfying(ClosingPendingConfirmationRequiredException.class,
                        error -> assertThat(error.pendingCount()).isEqualTo(3));
        assertThat(closingRows()).isEqualTo(rows);
        assertThat(closings.versions(A, "2026-10").versions()).hasSize(1);
    }

    @Test
    void v4AVersionWithoutChangesRefreshesLabelsAndTheOverdueDate() {
        matrix();
        var v1 = close(G, "2026-10", true).closing().saved();
        var category = categories.list(A, false).stream().filter(c -> c.id().equals(housing)).findFirst()
                .orElseThrow();
        tx.execute(status -> categories.rename(A, housing, category.version(), "Lar e contas"));
        assertThat(view(A, "2026-10").status()).isEqualTo("UP_TO_DATE");

        var result = generate(at(Instant.parse("2026-10-25T15:00:00Z")), A, 1, true, UUID.randomUUID());

        var v2 = result.closing().saved();
        assertThat(v2.version()).isEqualTo(2);
        assertThat(v2.contentDigest()).isEqualTo(v1.contentDigest());
        assertThat(v2.categories().getFirst().categoryName()).isEqualTo("Lar e contas");
        assertTotals(v2, 8, "2792.33", "180.00", 4, "962.33", 4, "1840.00", "180.00", 4, "1840.00");
        assertThat(v2.indicators().overdueEstimated()).isEqualTo("180.00");
        assertThat(result.closing().status()).isEqualTo("UP_TO_DATE");
        var first = closings.version(A, "2026-10", "1").snapshot();
        assertThat(first).isEqualTo(v1);
        assertThat(first.categories().getFirst().categoryName()).isEqualTo("Casa e contas");
        assertThat(first.indicators().overdueTotal()).isEqualTo("1560.00");
    }

    @Test
    void v5AStaleExpectedVersionIsRefused() {
        matrix();
        close(G, "2026-10", true);
        generate(at(LATER), A, 1, true, UUID.randomUUID());
        var rows = closingRows();
        assertThatThrownBy(() -> generate(at(LATER), G, 1, true, UUID.randomUUID()))
                .isInstanceOfSatisfying(ClosingVersionConflictException.class,
                        error -> assertThat(error.currentVersion()).isEqualTo(2));
        assertThat(closingRows()).isEqualTo(rows);
    }

    @Test
    void v6ConcurrentGenerationsCreateOneVersion() throws Exception {
        matrix();
        close(G, "2026-10", true);
        var later = at(LATER);
        var outcomes = race(() -> outcome(() -> generate(later, A, 1, true, UUID.randomUUID())),
                () -> outcome(() -> generate(later, G, 1, true, UUID.randomUUID())));
        assertThat(outcomes).containsExactlyInAnyOrder("CREATED", "ClosingVersionConflictException");
        assertThat(count("month_closing_versions")).isEqualTo(2);
        assertThat(count("month_closing_events")).isEqualTo(2);

        var key = UUID.randomUUID();
        var same = race(() -> outcome(() -> generate(later, A, 2, true, key)),
                () -> outcome(() -> generate(later, A, 2, true, key)));
        assertThat(same).containsExactlyInAnyOrder("CREATED", "REPLAYED");
        assertThat(closings.versions(A, "2026-10").versions()).extracting(ClosingVersionListView.Item::version)
                .containsExactly(1, 2, 3);
    }

    @Test
    void v7RepeatedRequestsReturnTheVersionAlreadyGenerated() {
        matrix();
        close(G, "2026-10", true);
        var key = UUID.randomUUID();
        var first = generate(at(LATER), A, 1, true, key);
        var repeated = generate(at(LATER), A, 1, true, key);
        assertThat(repeated.replayed()).isTrue();
        assertThat(repeated.closing().saved()).isEqualTo(first.closing().saved());
        assertThat(count("month_closing_versions")).isEqualTo(2);
        assertThatThrownBy(() -> generate(at(LATER), A, 2, true, key))
                .isInstanceOf(ClosingIdempotencyConflictException.class);
        assertThat(count("month_closing_versions")).isEqualTo(2);
    }

    @Test
    void v8OnlyClosedMonthsGetVersionsAndOnlyExistingVersionsAreRead() {
        matrix();
        close(G, "2026-10", true);
        assertThatThrownBy(() -> generate(at(LATER), A, "2026-09", 1, true, UUID.randomUUID()))
                .isInstanceOf(MonthNotClosedException.class);
        assertThatThrownBy(() -> closings.version(A, "2026-10", "5"))
                .isInstanceOf(ClosingVersionNotFoundException.class);
        for (var invalid : List.of("0", "x"))
            assertThatThrownBy(() -> closings.version(A, "2026-10", invalid))
                    .isInstanceOf(ReportQueryValidationException.class);
        assertThat(closings.versions(A, "2026-09").versions()).isEmpty();
        assertThat(closings.versions(A, "2026-09").currentVersion()).isNull();
        assertThatThrownBy(() -> close(A, "2026-10", true)).isInstanceOf(MonthAlreadyClosedException.class);
        assertThat(count("month_closing_versions")).isEqualTo(1);
    }

    @Test
    void v9AFailureKeepsThePreviousVersionInForce() {
        var data = matrix();
        close(G, "2026-10", true);
        settle(data.o2, "100.00", OCT_15, GUEST);
        var rows = closingRows();
        var failing = closings(new MonthClosingPostgresIT.FailingAuditRepository(new JdbcMonthClosingRepository(jdbc)),
                new JdbcExpenseReportQueries(jdbc), Clock.fixed(LATER, ZoneOffset.UTC));
        var key = UUID.randomUUID();
        assertThatThrownBy(() -> generate(failing, A, "2026-10", 1, true, key))
                .hasMessageContaining("simulated audit failure");
        assertThat(closingRows()).isEqualTo(rows);
        assertThat(jdbc.queryForObject("select current_version from month_closings", Integer.class)).isEqualTo(1);
        assertThat(view(A, "2026-10").saved().version()).isEqualTo(1);
        assertThat(view(A, "2026-10").status()).isEqualTo("OUTDATED");

        var retried = generate(at(LATER), A, 1, true, key);
        assertThat(retried.replayed()).isFalse();
        assertThat(retried.closing().saved().version()).isEqualTo(2);
    }

    @Test
    void v10OnlyTheChangesIncludedInTheNewVersionStopBeingFlagged() throws Exception {
        var data = matrix();
        close(G, "2026-10", true);
        settle(data.o2, "100.00", OCT_15, GUEST);
        // A settlement of O1 sent while the version is being generated waits for the space lock.
        var executor = Executors.newSingleThreadExecutor();
        var settlement = new AtomicReference<Future<?>>();
        var intercepting = closings(new JdbcMonthClosingRepository(jdbc), interceptingEntries(() -> {
            settlement.set(executor.submit(() -> settle(data.o1, "1500.00", OCT_15, ADMIN)));
            waitUntilBlockedOnTheSpaceLock();
        }), Clock.fixed(LATER, ZoneOffset.UTC));
        var v2 = generate(intercepting, A, "2026-10", 1, true, UUID.randomUUID()).closing().saved();
        settlement.get().get(30, TimeUnit.SECONDS);
        executor.shutdown();

        assertThat(line(v2, data.o2).status()).isEqualTo("PAID");
        assertThat(line(v2, data.o1).status()).isEqualTo("PENDING");
        var view = view(A, "2026-10");
        assertThat(view.status()).isEqualTo("OUTDATED");
        assertThat(view.changes()).extracting(change -> tuple(change.kind(), change.expenseId(), change.fields()))
                .containsExactly(tuple("CHANGED", data.o1, List.of("SITUATION", "PAID_AMOUNT")));
    }

    @Test
    void v11EarlierVersionsKeepTheirValuesAfterLaterVersions() {
        var data = matrix();
        var v1 = close(G, "2026-10", true).closing().saved();
        settle(data.o2, "100.00", OCT_15, GUEST);
        var v2 = generate(at(LATER), A, 1, true, UUID.randomUUID()).closing().saved();
        var stored = jdbc.queryForList("select * from month_closing_lines order by version_id, expense_id");
        cancel(data.o1);

        var v3 = generate(at(LATER), G, 2, true, UUID.randomUUID()).closing().saved();

        assertTotals(v3, 7, "1292.33", "180.00", 5, "1062.33", 2, "240.00", "180.00", 1, "60.00");
        assertThat(closings.version(A, "2026-10", "1").snapshot()).isEqualTo(v1);
        assertThat(closings.version(A, "2026-10", "2").snapshot()).isEqualTo(v2);
        assertThat(jdbc.queryForList("select * from month_closing_lines where version_id in "
                + "(select id from month_closing_versions where version_number < 3) order by version_id, expense_id"))
                .isEqualTo(stored);
        assertThat(closings.versions(A, "2026-10").versions()).extracting(ClosingVersionListView.Item::version,
                ClosingVersionListView.Item::current).containsExactly(tuple(1, false), tuple(2, false),
                tuple(3, true));
        assertThat(jdbc.queryForList("select distinct content_digest from month_closing_versions")).hasSize(3);
    }

    @Test
    void v12VersionsBelongToTheirSpace() {
        var data = matrix();
        close(G, "2026-10", true);
        close(O, "2026-10", true);
        tx.execute(status -> expenses.settle(O, new com.malyah.accountmanager.expenses.application
                .SettleExpenseCommand(data.foreign, expenses.get(O, data.foreign).version(), "500.00", OCT_15,
                OUTSIDER, null, UUID.randomUUID())));
        var foreign = generate(at(LATER), O, 1, false, UUID.randomUUID()).closing().saved();
        assertThat(foreign.version()).isEqualTo(2);
        assertThat(foreign.indicators().paidTotal()).isEqualTo("500.00");

        assertThat(closings.versions(A, "2026-10").versions()).hasSize(1);
        assertThat(closings.versions(O, "2026-10").versions()).hasSize(2);
        assertThat(view(A, "2026-10").saved().version()).isEqualTo(1);
        generate(at(LATER), A, 1, true, UUID.randomUUID());
        assertThat(closings.list(A, "2026").closings()).extracting(MonthClosingListView.Item::month,
                MonthClosingListView.Item::version, MonthClosingListView.Item::authorDisplayName,
                MonthClosingListView.Item::closedAt, MonthClosingListView.Item::status)
                .containsExactly(tuple("2026-10", 2, "Admin", LATER, "UP_TO_DATE"));
    }

    private MonthClosingUseCase at(Instant instant) {
        return closings(new JdbcMonthClosingRepository(jdbc), new JdbcExpenseReportQueries(jdbc),
                Clock.fixed(instant, ZoneOffset.UTC));
    }

    private static CloseMonthResult generate(MonthClosingUseCase useCase, String email, int expected,
            boolean acknowledge, UUID key) {
        return generate(useCase, email, "2026-10", expected, acknowledge, key);
    }

    private static CloseMonthResult generate(MonthClosingUseCase useCase, String email, String month, int expected,
            boolean acknowledge, UUID key) {
        return useCase.generateVersion(email, new GenerateVersionCommand(month, expected, acknowledge, key));
    }

    private static void assertTotals(ClosingSnapshotView snapshot, long planned, String plannedTotal,
            String plannedEstimated, long paid, String paidTotal, long pending, String pendingTotal,
            String pendingEstimated, long overdue, String overdueTotal) {
        var totals = snapshot.indicators();
        assertThat(totals.plannedCount()).isEqualTo(planned);
        assertThat(totals.plannedTotal()).isEqualTo(plannedTotal);
        assertThat(totals.plannedEstimated()).isEqualTo(plannedEstimated);
        assertThat(totals.paidCount()).isEqualTo(paid);
        assertThat(totals.paidTotal()).isEqualTo(paidTotal);
        assertThat(totals.pendingCount()).isEqualTo(pending);
        assertThat(totals.pendingTotal()).isEqualTo(pendingTotal);
        assertThat(totals.pendingEstimated()).isEqualTo(pendingEstimated);
        assertThat(totals.overdueCount()).isEqualTo(overdue);
        assertThat(totals.overdueTotal()).isEqualTo(overdueTotal);
    }
}
